### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rmarskell**
Fixed a rather important typo in the installation command.

### CODE REVIEW

**Comment by Thanaen** [comment]
It seems that this pull request is not longer needed, as they probably fixed this typo themselves instead of accepting your pull request, @rmarskell !

**Comment by Thanaen** [comment]
It seems that they aren't paying much attention to the pull requests 😕

**Comment by cb-goutham** [comment]
Fixed in the latest version 2.7.3.

**Comment by rmarskell** [comment]
I feel like it goes against the spirit of open source to look at people's PR's and then make the changes yourself but to each their own, I guess. Thanks for making the fix. <3

**Pull request closed without merging**
